### ISSUE TITLE
Was compiling, now errors

### ISSUE THREAD

**Issue by ashukie** [chirun-ncl/chirun#250] opened 2024-08-20 15:03 UTC
Hello, 

All tex files compiling through chirun without error before my summer break, but now all have errors. I have only changed a title, so unsure what the issue is. Any advice would be much appreciated.

Many thanks,
Alex

**Comment by christianp** [comment] 2024-08-23 12:44
I've removed the link to your material, since it grants anyone access to edit the package.

I'll look into the error now.

**Comment by christianp** [comment] 2024-08-23 13:13
I reproduced this error on the live server, but not on my development server. It looks like there are many builds that have failed with this error, so I don't think it's to do with the contents of the package.

I restarted the server while changing something in the admin view, and now I don't get the error any more. That's disappointing in one sense, because I can't work out what the error was, but if it was due to something like the task runner being stuck on an old version of the code, maybe the bug is already fixed.

Thanks for reporting this. I'll close the issue for now, but if we see this again I'll reopen it.

**Closed by christianp** 2024-08-23 13:13 UTC
